### ISSUE TITLE
   can you tell me how to port twrp for walton primo h8 turbo?

### ISSUE THREAD

**Issue by sami777yt** [theintel/twrpwaltonprimoh8#9]
@theintel   can you tell me how to port twrp for walton primo h8 turbo?

**Comment by theintel** [comment]
@sami777yt I already have ported a working twrp recovery for this device. I'll write a tutorial in this repository along with necessary resources for porting the recovery yourself. Or I can share the ported recovery if you need it.

**Comment by sami777yt** [comment]
> @sami777yt I already have ported a working twrp recovery for this device. I'll write a tutorial in this repository along with necessary resources for porting the recovery yourself. Or I can share the ported recovery if you need it.

@theintel  Yes, I need this. Please give the ported twrp.

**Comment by theintel** [comment]
https://file.io/auW33Gal1wzI
 Except some minor bugs, it works just fine. But remember, don't flash it without unlocking bootloader.

**Comment by sami777yt** [comment]
> https://file.io/auW33Gal1wzI Except some minor bugs, it works just fine. But remember, don't flash it without unlocking bootloader.

I entered the link it shows the file is deleted

**Comment by theintel** [comment]
My bad. I re-uploaded the file: https://file.io/O2SwxlM8dRBJ

**Comment by sami777yt** [comment]
> My bad. I re-uploaded the file: https://file.io/O2SwxlM8dRBJ

Thank you.
